FROM golang:1.25 AS builder

WORKDIR /app


COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o kubemanager ./cmd/gateway/main.go

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /app/kubemanager .
COPY internal/core/configs /app/internal/core/configs

COPY internal/infrastructure/database/migrations ./migrations

USER appuser

EXPOSE 8080
CMD ["./kubemanager"]
