DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS user_sessions;

DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS users;


DROP EXTENSION IF EXISTS "uuid-ossp";