// Code generated by go generate; DO NOT EDIT.
package domain

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
)

var (
	// ErrInvalidPermissionType is the error returned when the value does not exist in the enum.
	ErrInvalidPermissionType = errors.New("invalid value for PermissionType")
)

type PermissionType struct {
	value string
}

func (f PermissionType) String() string {
	return f.value
}

// FromString parses a string to fill the current struct.
func (f *PermissionType) FromString(ctx context.Context, str string) error {
	if f == nil {
		return fmt.Errorf("PermissionType must not be nil")
	}
	var err error
	*f, err = PermissionTypes.NewFromString(ctx, str)
	return err
}

// MarshalJSON implements the json.Marshaler interface.
func (f PermissionType) MarshalJSON() ([]byte, error) {
	res := f.String()
	if res == "" {
		return []byte("null"), nil
	}

	res = "\"" + res + "\""
	return []byte(res), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (f *PermissionType) UnmarshalJSON(b []byte) error {
	var s string
	err := json.Unmarshal(b, &s)
	if err != nil {
		return fmt.Errorf("unmarshal failed: %w", err)
	}

	if s == "" {
		return nil
	}

	res, err := PermissionTypes.NewFromString(context.Background(), s)
	if err != nil {
		return err
	}

	*f = res
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface.
func (s PermissionType) MarshalText() (text []byte, err error) {
	return []byte(s.value), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (s *PermissionType) UnmarshalText(text []byte) error {
	res, err := PermissionTypes.NewFromString(context.Background(), string(text))
	if err != nil {
		return err
	}

	*s = res
	return nil
}

func (f PermissionType) IsZero() bool {
	return f.value == ""
}

// PermissionTypes contains all possible values for the enum.
var PermissionTypes = permissionTypes{

	LogsView:       PermissionType{value: "k8s:logs:view"},
	ShellExec:      PermissionType{value: "k8s:shell:exec"},
	WorkloadCreate: PermissionType{value: "k8s:workload:create"},
	WorkloadDelete: PermissionType{value: "k8s:workload:delete"},
	ProjectDelete:  PermissionType{value: "project:delete"},
	ProjectEdit:    PermissionType{value: "project:edit"},
	ProjectView:    PermissionType{value: "project:view"},
}

// permissionTypes is the struct containing the static values.
type permissionTypes struct {
	LogsView       PermissionType
	ShellExec      PermissionType
	WorkloadCreate PermissionType
	WorkloadDelete PermissionType
	ProjectDelete  PermissionType
	ProjectEdit    PermissionType
	ProjectView    PermissionType
}

// NewFromString validates and returns the enum corresponding to the string.
func (f permissionTypes) NewFromString(ctx context.Context, str string) (PermissionType, error) {
	switch str {
	case "k8s:logs:view":
		return f.LogsView, nil
	case "k8s:shell:exec":
		return f.ShellExec, nil
	case "k8s:workload:create":
		return f.WorkloadCreate, nil
	case "k8s:workload:delete":
		return f.WorkloadDelete, nil
	case "project:delete":
		return f.ProjectDelete, nil
	case "project:edit":
		return f.ProjectEdit, nil
	case "project:view":
		return f.ProjectView, nil
	default:
		return PermissionType{}, fmt.Errorf("%w: %s", ErrInvalidPermissionType, str)
	}
}

func (f permissionTypes) All() []PermissionType {
	return []PermissionType{
		f.LogsView,
		f.ShellExec,
		f.WorkloadCreate,
		f.WorkloadDelete,
		f.ProjectDelete,
		f.ProjectEdit,
		f.ProjectView,
	}
}
